* Jour 14: Redoubt de salle 

L'un des historiens a besoin d'utiliser la salle de bains; heureusement, vous savez, il y a une salle de bains près d'un endroit non visité sur leur liste, et donc vous êtes tous rapidement téléportés directement dans le hall du siège de Pâque Bunny.

Malheureusement, l'EBHQ semble avoir "amélioré" la sécurité des toilettes après votre dernière visite. La zone à l'extérieur de la salle de bains fourmille de robots.

Pour amener The Historian en toute sécurité aux toilettes, vous aurez besoin d'un moyen de prédire où les robots seront à l'avenir. Heureusement, ils semblent tous se déplacer sur le sol de la tuile en ligne droite prévisible.

Vous faites une liste (votre entrée de puzzle) de tous les robots actuels Positions (p) et les vitesses (v), un robot par ligne. Par exemple:

p=0,4 v=3,-3
p=6,3 v=-1,-3
p=10,3 v=-1,2
p=2,0 v=2,-1
p=0,0 v=1,3
p=3,0 v=-2,-2
p=7,6 v=-1,-3
p=3,0 v=-1,-2
p=9,3 v=2,3
p=7,3 v=-1,2
p=2,4 v=2,-3
p=9,5 v=-3,-3

La position de chaque robot est donnée comme p=x,y lorsque x représente le nombre de tuiles que le robot vient de la paroi gauche et y représente le nombre de tuiles à partir du mur supérieur (lorsqu'on les voit de dessus). Donc, une position de p=0,0 signifie que le robot est tout le chemin dans le coin supérieur gauche.

La vitesse de chaque robot est donnée comme v=x,y lorsque x et y sont indiqués en carreaux par seconde. Positif x signifie que le robot se déplace vers le droit, et positifs y signifie que le robot se déplace vers le bas. Donc, une vitesse de v=1,-2 signifie que chaque seconde, le robot se déplace 1 carreaux à droite et 2 tuiles en haut.

Les robots à l'extérieur de la salle de bain réelle sont dans un espace qui est 101 carreaux larges et 103 carreaux de taille haute (en vue de dessus). Cependant, dans cet example, les robots sont dans un espace qui n'est que 11 carreaux larges et 7 carreaux de grande taille.

Les robots sont bons pour naviguer/sous les uns les autres (en raison d'une combinaison de ressorts, de jambes extensibles et de quadcoptères), de sorte qu'ils peuvent partager la même tuile et ne pas interagir les uns avec les autres. Visuellement, le nombre de robots sur chaque tuile dans cet exemple ressemble à ceci:

1.12.......
...........
...........
......11.11
1.1........
.........1.
.......1...

Ces robots ont une caractéristique unique pour une sécurité maximale de la salle de bains: ils peuvent téléports. Quand un robot courait dans un bord de l'espace dans lequel ils sont, ils sont à la place téléporter vers l'autre face, enrouler efficacement autour des bords. Voici quel robot p=2,4 v=2,-3 fait pour les premières secondes:

Initial state:
...........
...........
...........
...........
..1........
...........
...........

After 1 second:
...........
....1......
...........
...........
...........
...........
...........

After 2 seconds:
...........
...........
...........
...........
...........
......1....
...........

After 3 seconds:
...........
...........
........1..
...........
...........
...........
...........

After 4 seconds:
...........
...........
...........
...........
...........
...........
..........1

After 5 seconds:
...........
...........
...........
.1.........
...........
...........
...........

L'historien ne peut pas attendre beaucoup plus longtemps, donc vous n'avez pas à simuler les robots pendant très longtemps. Où les robots seront-ils après 100 secondes ?

Dans l'exemple ci-dessus, le nombre de robots sur chaque tuile après 100 secondes s'est écoulé comme suit:

......2..1.
...........
1..........
.11........
.....1.....
...12......
.1....1....

Pour déterminer la zone la plus sûre, comptez le nombre de robots dans chaque quadrant après 100 secondes. Les robots qui sont exactement au milieu (horizontalement ou verticalement) ne comptent pas comme étant dans un quadrant, de sorte que les seuls robots pertinents sont:

..... 2..1.
..... .....
1.... .....
           
..... .....
...12 .....
.1... 1....

Dans cet example, les quadrants contiennent 1, 3, 4, et 1 robot. La multiplication de ceux-ci ensemble donne un total facteur de sécurité de 12.

Prédire le mouvement des robots dans votre liste dans un espace qui est 101 carreaux larges et 103 carreaux de grande taille. Quel sera le facteur de sécurité après l'expiration d'une centaine de secondes précises?


** Réponse Partie 1 : 208437768


* Deuxième partie 

Pendant la pause de la salle de bains, quelqu'un remarque que ces robots semblent terriblement similaires à ceux construits et utilisés au pôle Nord. S'ils sont le même type de robots, ils devraient avoir un œuf de Pâques codé en dur : très rarement, la plupart des robots devraient s'arranger en une image d'un sapin.

Quel est le plus petit nombre de secondes qui doit s'écouler pour que les robots affichent l'œuf de Pâques ?


** Réponse Partie 2 : 7492
